services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docmatch_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://ovjbbjiqbvelmsfsexko.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92amJiamlxYnZlbG1zZnNleGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NTc2MTIsImV4cCI6MjA5MjQzMzYxMn0.kODigivmBC21pRpoNuEHeYmMj3oLSEPkYYAGe2c1vTE
    container_name: docmatch_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://ovjbbjiqbvelmsfsexko.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92amJiamlxYnZlbG1zZnNleGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NTc2MTIsImV4cCI6MjA5MjQzMzYxMn0.kODigivmBC21pRpoNuEHeYmMj3oLSEPkYYAGe2c1vTE
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: docmatch_network
